# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "Download boost 1.77.0"
        run: |
          wget -O boost.tar.bz2 https://sourceforge.net/projects/boost/files/boost/1.77.0/boost_1_77_0.tar.bz2 
          tar -xf boost.tar.bz2 --checkpoint=.100
          rm boost.tar.bz2
      
      - name: "Checkout bzip2 1.0.8"
        uses: actions/checkout@v2
        with:
          repository: 'dankmolot/bzip2'
          ref: 'bzip2-1.0.8'
          path: 'bzip2'

      - name: 'Compile bzip2'
        run: |
          cd bzip2
          make libbz2.a
      
      - name: 'Compile boost'
        run: |
          cd boost_1_77_0
          ./bootstrap.sh
          LD_LIBRARY_PATH=${{ github.workspace }} ./b2 variant=release link=static cflags=-fPIC cxxflags=-fPIC --with-iostreams
          
